###
GET http://localhost:3333/users
###
POST http://localhost:3333/user
Content-Type: application/json

{
  "email": "jason98.bae@gmail.com",
  "password": "sung1761",
  "gender": "male",
  "age": 39
}
