###
GET http://localhost:3333/users
###
POST http://localhost:3333/user
Content-Type: application/json

{
  "email": "jason98.bae@gmail.com",
  "password": "sung1761",
  "gender": "male",
  "age": 39
}

###
POST http://localhost:3333/api/login
Content-Type: application/json

{
  "email": "jason98.bae@gmail.com",
  "password": "sung1761"
}


###
GET http://localhost:3333/api/protected
Authorization: JWT eyJhbGciOiJIUzI1NiJ9.c29tZSBwYXlsb2Fk.TqRWoJaQfuYTiogiuQ7KSajkqNmMKi7YQwwDUunRcgA
